config/routes.rb
Rails.application.routes.draw do
	resources :fridges do
		resources :frozen_servings, only: [:new, :create]
		resources :fridge_ingredients, only: [:new, :create]
		get '/analytics', to: "fridges#analytics", as: "analytics"
	end

	post '/fridges/:id/throwaway', to: "fridges#throwaway", as: "throwaway"
	post '/fridges/:id/eat_meals', to: "fridges#eat_meals", as: "eat_meals"
	post '/fridges/:id/eat_ingredients', to: "fridges#eat_ingredients", as: "eat_ingredients"
	get '/', to: "sessions#new"
	post '/', to: "sessions#create"
	get '/signup', to: "fridges#new"
	post '/signup', to: "fridges#create"
	post '/logout', to: "sessions#destroy"

end

app/models/fridge.rb
class Fridge < ApplicationRecord
	has_secure_password
	has_many :fridge_ingredients
	has_many :ingredients, through: :fridge_ingredients
	has_many :frozen_servings
	has_many :recipes, through: :frozen_servings

	validates :name, uniqueness: true

	def expired_fridge_ingredients
		self.fridge_ingredients.each do |ingredient|
			if ingredient.days_until_expiration < 0
				ingredient.expired = true
				ingredient.save
			end
		end
	end

	def expired_frozen_servings
		self.frozen_servings.each do |meal|
			if meal.days_until_expiration < 0
				meal.expired = true
				meal.save
			end
		end
	end

	def toss
		self.fridge_ingredients.where(expired: true).each do |ingredient|
			ingredient.date_out = Date.today
			ingredient.save
		end
		self.frozen_servings.where(expired: true).each do |meal|
			meal.date_out = Date.today
			meal.save
		end
	end

	def eat_meals(meal_array)
		meal_array.each do |meal|
			eaten_meal = frozen_servings.find(meal)
			eaten_meal.date_out = Date.today
			eaten_meal.save
		end
	end

	def eat_ingredients(ingredient_array)
		ingredient_array.each do |ingredient|
			eaten_ingredient = fridge_ingredients.find(ingredient)
			eaten_ingredient.date_out = Date.today
			eaten_ingredient.save
		end
	end

	def sort_fridge_ingredients(sort_method)
		self.expired_fridge_ingredients
		if sort_method.nil? || sort_method == "DATE ASC"
			self.fridge_ingredients.where(expired: false).order(:date_in)
		elsif sort_method == "DATE DESC"
			self.fridge_ingredients.where(expired: false).order(date_in: :desc)
		elsif sort_method == "NAME"
			self.fridge_ingredients.where(expired: false).joins(:ingredient).order("name")
		elsif sort_method == "EXP ASC"
			self.ordered_fridge_ingredients
		elsif sort_method == "EXP DESC"
			self.ordered_fridge_ingredients.reverse
		end
	end

	def ordered_hash_fridge_ingredients
		unordered = self.fridge_ingredients.where(expired: false).inject({}) do |acc, ingredient|
			acc[ingredient.id] = ingredient.days_until_expiration
			acc
		end
		unordered.sort_by { |k, v| v}
	end

	def ordered_fridge_ingredients
		self.ordered_hash_fridge_ingredients.map do |pair|
			self.fridge_ingredients.find(pair[0])
		end
	end

	def sort_frozen_servings(sort_method)
		self.expired_frozen_servings
		if sort_method.nil? || sort_method == "DATE ASC"
			self.frozen_servings.where(expired: false).order(:date_in)
		elsif sort_method == "DATE DESC"
			self.frozen_servings.where(expired: false).order(date_in: :desc)
		elsif sort_method == "NAME"
			self.frozen_servings.where(expired: false).joins(:recipe).order("name")
		elsif sort_method == "EXP ASC"
			self.ordered_frozen_servings
		elsif sort_method == "EXP DESC"
			self.ordered_frozen_servings.reverse
		end
	end

	def ordered_hash_frozen_servings
		unordered = self.frozen_servings.where(expired: false).inject({}) do |acc, meal|
			acc[meal.id] = meal.days_until_expiration
			acc
		end
		unordered.sort_by { |k, v| v}
	end

	def ordered_frozen_servings
		self.ordered_hash_frozen_servings.map do |pair|
			self.frozen_servings.find(pair[0])
		end
	end

	def meals_expiring_most_often
		top_5 = self.frozen_servings.group("recipe_id", "frozen_servings.id").having(expired: true).order("count (*) DESC").first(5)
		top_5.inject({}) do |acc, meal|
			acc[meal.recipe.name] = self.frozen_servings.where("recipe_id = #{meal.recipe_id}").where(expired: true).count
			acc
		end

	end

	def ingredients_expiring_most_often
		top_5 = self.fridge_ingredients.group("ingredient_id", "fridge_ingredients.id").having(expired: true).order("count (*) DESC").first(5)
		top_5.inject({}) do |acc, ingredient|
			acc[ingredient.ingredient.name] = self.fridge_ingredients.where("ingredient_id = #{ingredient.ingredient_id}").where(expired: true).count
			acc
		end
	end

	def most_frequent_meals
		top_5 = self.frozen_servings.where(expired: false).where("date_out IS NOT NULL").group("recipe_id", "frozen_servings.id").order("count (*) DESC").first(5)
		top_5.inject({}) do |acc, meal|
			acc[meal.recipe.name] = self.frozen_servings.where("recipe_id = #{meal.recipe_id}").where(expired: false).where("date_out IS NOT NULL").count
			acc
		end
	end

	def most_frequent_ingredients
		top_5 = self.fridge_ingredients.where(expired: false).where("date_out IS NOT NULL").group("ingredient_id", "fridge_ingredients.id").order("count (*) DESC").first(5)
		top_5.inject({}) do |acc, ingredient|
			acc[ingredient.ingredient.name] = self.fridge_ingredients.where("ingredient_id = #{ingredient.ingredient_id}").where(expired: false).where("date_out IS NOT NULL").count
			acc
		end
	end

end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController

before_action :authorized, except: [:new, :create]

	def new
		@fridge = Fridge.new
	end

	def create
		@fridge = Fridge.new(fridge_params)

		if @fridge.save
			redirect_to fridge_path(@fridge)
			session[:fridge_id] = @fridge.id
		else
			redirect_to '/signup'
		end

	end

	def show
		@previous_selection = params[:sort]
		@fridge = Fridge.find(params[:id])
		@fridge_ingredients = @fridge.sort_fridge_ingredients(params[:sort])
		@frozen_servings = @fridge.sort_frozen_servings(params[:sort])
	end

	def throwaway
		@fridge = Fridge.find(params[:id])
		@fridge.toss
		redirect_to fridge_path(@fridge)
	end

	def eat_meals
		@fridge = Fridge.find(params[:id])
		if params[:eat_meals].nil?
			redirect_to fridge_path(@fridge)
		else
			@fridge.eat_meals(params[:eat_meals])
			redirect_to fridge_path(@fridge)
		end
	end

	def eat_ingredients
		@fridge = Fridge.find(params[:id])
		if params[:eat_ingredients].nil?
			redirect_to fridge_path(@fridge)
		else
			@fridge.eat_ingredients(params[:eat_ingredients])
			redirect_to fridge_path(@fridge)
		end
	end

	def analytics
		@fridge = Fridge.find(params[:fridge_id])
		@meals_expiring_most_often = @fridge.meals_expiring_most_often
		@ingredients_expiring_most_often = @fridge.ingredients_expiring_most_often
		@most_frequent_meals = @fridge.most_frequent_meals
		@most_frequent_ingredients = @fridge.most_frequent_ingredients
	end

	private

	def authorized
		if !logged_in?
			redirect_to '/fridges/new'
		end
	end

	def fridge_params
    params.require(:fridge).permit(:name, :password, :password_confirmation)
  end

end

app/views/fridges/analytics.html.erb
<h1><b>Your Fridge Analytics</h1></b>
<br>
<h2>Items Expiring Most Often</h2>

<div class="row">
<div class="col-lg-6">
<h3> Meals </h3>
	<table class="table table-striped table-bordered table-hover">
	  <tr>
	    <th>Name</th>
	    <th>Times Expired</th>
	  </tr>
				<% @meals_expiring_most_often.each do |k, v| %>
		<tr>
	    <td><%= k %></td>
	    <td><%= v %></td>
		</tr>
				<% end %>
	</table>
</div>

<div class="col-lg-6">
<h3> Ingredients </h3>
	<table class="table table-striped table-bordered table-hover">
		 <tr>
		   <th>Name</th>
		   <th>Times Expired</th>
		 </tr>
				<% @ingredients_expiring_most_often.each do |k, v| %>
		<tr>
		   <td><%= k %></td>
		   <td><%= v %></td>
		</tr>
				<% end %>
	</table>
</div>
</div>


<h2> Most Frequently Eaten Items </h2>

<div class="row">
<div class="col-lg-6">
<h3> Meals </h3>
	<table class="table table-striped table-bordered table-hover">
	  <tr>
	    <th>Name</th>
	    <th>Times Eaten</th>
	  </tr>
				<% @most_frequent_meals.each do |k, v| %>
		<tr>
	    <td><%= k %></td>
	    <td><%= v %></td>
		</tr>
				<% end %>
	</table>
</div>

<div class="col-lg-6">
<h3> Ingredients </h3>
	<table class="table table-striped table-bordered table-hover">
		 <tr>
		   <th>Name</th>
		   <th>Times Eaten</th>
		 </tr>
				<% @most_frequent_ingredients.each do |k, v| %>
		<tr>
		   <td><%= k %></td>
		   <td><%= v %></td>
		</tr>
				<% end %>
	</table>
</div>
</div>

app/views/fridges/new.html.erb
<div class="row">
	<div class="col-lg-6">
		<img src= <%= image_path('/images/fridge.png') %>>
	</div>

<h1><b>Sign Up</b></h1>
<br>
<div class="col-lg-6">
	<%= form_for @fridge do |f| %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>
<div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>
	<%= f.submit class: "btn-info" %>
	<% end %>
	</div>
</div>

app/views/fridges/show.html.erb
<div class="row">
	<div class="col-lg-6">
		<h1><b><%= @fridge.name %>'s Fridge</h1></b>
</div>

<div class="col-lg-6">
	<p>Play Greeting Message:<audio controls>
  	<source src= <%= audio_path('/audios/Fridgey.m4a') %> type="audio/mpeg">
		</audio></p>
	</div>
</div>

<br>
<br>

<%= form_tag fridge_path(@fridge), method: :get do %>
<%= select_tag(:sort, options_for_select([["Expiring Soonest", "EXP ASC"], ["Most Days Until Expiration", "EXP DESC"], ["Name", "NAME"], ["Recently Added", "DATE DESC" ], ["In Fridge Longest", "DATE ASC"]], @previous_selection)) %>
<%= submit_tag "Sort" %>
<% end %>

<br>
<br>

<div class="row">
<div class="col-lg-6">
<h2>Frozen Meals </h2>
	<table class="table table-striped table-bordered table-hover">
		<tr>
			<th>Delete</th>
	    <th>Name</th>
	    <th>Date In</th>
	    <th>Days Until Expiration</th>
	  </tr>
			<%= form_tag eat_meals_path(@fridge) do %>
				<% @frozen_servings.each do |meal| %>
					<% if meal.date_out.nil? %>
		<tr>
			<td><%= check_box_tag("eat_meals[]", meal.id) %></td>
	    <td><%= meal.recipe.name %></td>
	    <td><%= meal.date_in.strftime("%m/%d") %></td>
	    <td><%= meal.expiration_message %></td>
		</tr>
					<% end %>
				<% end %>
			<%= submit_tag "Eat Meals", class: "btn-info" %>
		<% end %>
	<%= link_to "Add a Meal", new_fridge_frozen_serving_path(@fridge), method: :get, class: "btn-info"%>
	</table>
</div>

<div class="col-lg-6">
<h2>Ingredients</h2>
	<table class="table table-striped table-bordered table-hover">
	  <tr>
			<th>Delete</th>
	    <th>Name</th>
	    <th>Date In</th>
	    <th>Days Until Expiration</th>
	  </tr>
			<%= form_tag eat_ingredients_path(@fridge) do %>
				<% @fridge_ingredients.each do |ingredient| %>
					<% if ingredient.date_out.nil? %>
		<tr>
			<td><%= check_box_tag("eat_ingredients[]", ingredient.id) %></td>
	    <td><%= ingredient.ingredient.name %></td>
	    <td><%= ingredient.date_in.strftime("%m/%d") %></td>
	    <td><%= ingredient.expiration_message %></td>
		</tr>
					<% end %>
	 			<% end %>
			<%= submit_tag "Eat Ingredients", class: "btn-info" %>
		<% end %>
	<%= link_to "Add an Ingredient", new_fridge_fridge_ingredient_path(@fridge), method: :get, class: "btn-info" %>
	</table>
	</div>
</div>


<h2>Expired Items</h2>
<%= button_to "Throw Out Expired Items", throwaway_path(@fridge), method: :post, class: "btn-info" %>
<table class="table table-striped table-bordered table-hover">
	<tr>
		<th>Name</th>
		<th>Days Expired</th>
	</tr>
		<% if !@fridge.expired_frozen_servings.empty? %>
			<% @fridge.frozen_servings.where(expired: true).where(date_out: nil).each do |meal| %>
	<tr>
		<td><%= meal.recipe.name %></td>
		<td><%= meal.expiration_message %></td>
	</tr>
			<% end %>
		<% end %>

		<% if !@fridge.expired_fridge_ingredients.empty? %>
			<% @fridge.fridge_ingredients.where(expired: true).where(date_out: nil).each do |ingredient| %>
	<tr>
		<td><%= ingredient.ingredient.name %></td>
		<td><%= ingredient.expiration_message %></td>
	</tr>
			<% end %>
		<% end %>
</table>