config/routes.rb
Rails.application.routes.draw do
	resources :fridges do
		resources :frozen_servings, only: [:new, :create]
		resources :fridge_ingredients, only: [:new, :create]
		get '/analytics', to: "fridges#analytics", as: "analytics"
	end

	post '/fridges/:id/throwaway', to: "fridges#throwaway", as: "throwaway"
	post '/fridges/:id/eat_meals', to: "fridges#eat_meals", as: "eat_meals"
	post '/fridges/:id/eat_ingredients', to: "fridges#eat_ingredients", as: "eat_ingredients"
	get '/', to: "sessions#new"
	post '/', to: "sessions#create"
	get '/signup', to: "fridges#new"
	post '/signup', to: "fridges#create"
	post '/logout', to: "sessions#destroy"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fridgey</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=""><b>F R I D G E Y</b></a>
    </div>
    <ul class="nav navbar-nav">
      <% if session[:fridge_id] %>
        <li><%= link_to "My Fridge", fridge_path(session[:fridge_id]) %></li>
        <li><%= link_to "Analytics", fridge_analytics_path(session[:fridge_id]) %></li>
        <li><%= link_to "Log Out", '/logout', method: :post %></li>
      <% elsif current_page?('/') %>
        <li><%= link_to "Sign Up", '/signup' %></li>
      <% elsif current_page?('/signup') %>
        <li><%= link_to "Log In", '/' %></li>
      <% end %>
    </ul>
  </div>
</nav>



    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>